### ISSUE TITLE
DART SDK is not configured

### ISSUE THREAD

**Issue by sakshamsolanki22** [londonappbrewery/mi_card_flutter#13]
I followed the steps provided by app brewery. But I get this message as soon as I launch the fluuter project in android studio
![IMG_20200326_224250820](https://user-images.githubusercontent.com/49778076/77682985-c0100980-6fbd-11ea-983d-4f5d9ae4ba9e.jpg)

**Comment by rachittt** [comment]
meme material

**Comment by Aghiles97** [comment]
Dont import the project. build it on your own0

**Comment by sakshamsolanki22** [comment]
> meme material

thanks bruv

**Comment by divyanshuk10** [comment]
You can create a new flutter project or open existing flutter project which is already running. And then follow the below steps.
goto any other flutter project click on File >> Settings >> Languages & Frameworks >> Dart >> COPY THE DART SDK PATH FROM THAT PROJECT AND PASTE IT INTO mi_card_flutter clone project. Try if it works

![Screenshot from 2023-02-21 09-43-33](https://user-images.githubusercontent.com/19980597/220246141-87a17380-c2c9-4718-bc70-72ee8e9323a8.png)


![Screenshot from 2023-02-21 09-47-53](https://user-images.githubusercontent.com/19980597/220246558-646d2979-fa0a-42b6-8807-4daf62caa724.png)
