### ISSUE TITLE
Gradle does not have execution permission

### ISSUE THREAD

**Issue by nexinet** [londonappbrewery/mi_card_flutter#2]
Hi
once starting emulator I got:
`Launching lib/main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...
[!] Gradle does not have execution permission.
    You should change the ownership of the project directory to your user, or move the project to a directory with execute permissions.
Finished with error: Gradle task assembleDebug failed with exit code 1
`
Any fixing?

**Comment by nexinet** [comment]
I use Android Studio with UBUNTU and Flutter.

**Comment by njworks** [comment]
You may want to try this -> [https://flutter.dev/docs/development/androidx-migration]
Also try adding: android.useAndroidX=true to mi_card_flutter/android/gradle.properties

If both doesn't work, you can always start a new project in Android studio and copy the main.dart code over from this repository.

**Comment by Dkm093** [comment]
I have the same issue but I do not have the option: 
File-->Sync Project with Gradle Files
my option is:
File-->Sync with file system.
I tried that and it does not work. Catalina with Android Studio 3.5.3
Any information on why this is an issue is appreciated. Thank you

**Comment by Lincxx** [comment]
There is also this suggestion from the Udemy course from a user name Max

OK ... seems to be a problem with androidx, whatever that might be.



Not sure if via Git created projects are not AndroidX projects at all, or if it's a recent change.



Added in Android/gradle.properties 2 lines: (Flutter, now with AndroidX)

android.useAndroidX=true
android.enableJetifier=true
Edited in Android/app/build.gradle 1 line: (Migrate to androidX)

compileSdkVersion 27 to
compileSdkVersion 28
I'm using Api 27 as Virtual device (An. 8.1) and compileSdkVersion must be greater - I think I read it somewhere.


Hope it helps,

Max

**Comment by krstbtk** [comment]
Had the same problem, did what Lincxx suggested and that helped!

Added in Android/gradle.properties 2 lines: (Flutter, now with AndroidX)

android.useAndroidX=true
android.enableJetifier=true

Edited in Android/app/build.gradle 1 line: (Migrate to androidX)

compileSdkVersion 27 to
compileSdkVersion 28

**Comment by justinalberta** [comment]
Here is what I did:

Wasn't able to get program to work on virtual android device. Tracked the problem down to needing to update project to work with AndroidX.

To get these working as is, I had to open the internal project's "android" file up as an existing project (not the mi_card_flutter file). Go into build.gradle and change compileSdkVersion to "28", then in Android Studio menu Refactor -> AndroidX and update any thing else that pops up.

**Comment by TheMuellenator** [comment]
Stub is updated now so this issue should be fixed.

**Comment by mirmahfuz99** [comment]
This error is gradle permission related . 
Just paste below line in your terminal and run...

chmod a+rx android/gradlew

**Comment by AviGadhiya** [comment]
I ran chmod a+rx android/gradlew but, did not work.

**Comment by pnk0006** [comment]
same issue.
[!] Gradle does not have execution permission.
    You should change the ownership of the project directory to your user, or move the project to a directory with execute permissions.
Gradle task assembleDebug failed with exit code 1

**Comment by AviGadhiya** [comment]
> same issue.
> [!] Gradle does not have execution permission.
> You should change the ownership of the project directory to your user, or move the project to a directory with execute permissions.
> Gradle task assembleDebug failed with exit code 1

Hi @pnk0006,
My flutter is working and my issue is solve,
Do one thing make your flutter project in different drive of hard disk, or make different partition,
IT IS WORK FOR ME,. I hope your problem will solve with this.

**Comment by cletusajibade** [comment]
`chmod a+rx android/gradlew ` worked for me just as @mirmahfuz99 mentioned above.

**Comment by pmunozroa** [comment]
```chmod a+rx android/gradlew``` worked for me, MacOS Catalina 10.15.4, thank you @mirmahfuz99

**Comment by heinaungzan** [comment]
how run chmod in terminal where path?

**Comment by scugn1zz0** [comment]
> how run chmod in terminal where path?

@heinaungzan you have to be in the folder project where the folder android is located, you can also do that opening the project in AndroidStudio and running it from the Terminal that AndroidStudio provides

**Comment by ibraBouguera** [comment]
@heinaungzan run chmod a+rx android/gradlew from the project path 
cd "INTO_YOUR_PROJECT_FOLDER"
chmod a+rx android/gradlew

**Comment by MechanicalNoob05** [comment]
I did the mentioned method above i.e. ```chmod a+rx android/gradlew ``` but it didn't work so i went for digging and just replaced the trouble making  build.gradle files in   android/app and android/ with an existing working build.gradle  file which i used in a prior project
and it seems to work.
