### ISSUE TITLE
can not run mi_card downloaded from here, doesn't work. Need help

### ISSUE THREAD

**Issue by calystary** [londonappbrewery/mi_card_flutter#53]
Hi, after downloading mi_card from link provided in the course, when trying to run it getting this message:

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:

     The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.window:window-java:1.0.0-beta04.
     AAR metadata file: C:\Users\lulu\.gradle\caches\transforms-3\41a83d0cf61e3d2ab42ea706b65148ab\transformed\jetified-window-java-1.0.0-beta04\META-INF\com\android\build\gradle\aar-metadata.properties.

     The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.window:window:1.0.0-beta04.
     AAR metadata file: C:\Users\lulu\.gradle\caches\transforms-3\bb9a53f8c4dc071c681fa071739dc70b\transformed\jetified-window-1.0.0-beta04\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by bhavukkalra** [comment]
Hi, For Windows users this seems have been caused by the 2nd Commit Repository. Which seems to update the gradle files.
Solution - Just revert back to the Initial commit and then try building again(It worked for me!)

Command - `git checkout -b new_branch b7f3aa688bf398829a4de914273d3162b300cb4c`

What It will do is create a new branch at the Initial commit and change the codebase accordingly.

**Comment by calystary** [comment]
Thank You for Your reply. I’m a very beginner and don’t even know what commit is and how to revert it. Would You be so kind and tell me step by step what to do, please?

Wysłane z iPhone'a

**Comment by bhavukkalra** [comment]
No Problem but first few things that you must check on your pc.
1) You must have installed git while downloading flutter SDK. check if it is installed by running git on Powershell(if, on windows) or git on Terminal(if on MAC/LINUX). If it is not working I would advice installing git via a tutorial.
2) Once that is done, Open a Terminal/Powershell window in the folder that you have downloaded the project in and run this command in the terminal

`git checkout -b new_branch b7f3aa688bf398829a4de914273d3162b300cb4c`

3) Now open the project in Android Studio -> Pub Get Dependencies -> Build and Run the Project on a Device.

I hope this detailed explanation helped you in some way. If you are stuck on any of the above mentioned points. Feel free to reach out!

**Comment by calystary** [comment]
Thank You very much, it worked ;)

**Comment by calystary** [comment]
Could You tell me what that string means : b7f3aa688bf398829a4de914273d3162b300cb4c
where did You get that string from?

**Comment by UsmanAsad87** [comment]
thanks, i encountered the same problem but solved with your help

**Comment by bhavukkalra** [comment]
Sure @calystary. So in Version Control each state of the project is referenced with the name of `Commit` and to uniquely Identify each commit. They are given a unique Hash Key. So the string that you got there `b7f3aa6` is the unique identifier of the first commit.

This is a very high level overview of what a commit is and what is a hash key. I would recommend to search up git on Youtube and learn more on it and get your hands dirty with it. 

Cheers Bhavuk

**Comment by calystary** [comment]
Thanks @bhavukkalra.
