### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by raghadromaneh** [londonappbrewery/mi_card_flutter#57]
what should i do ?
please , step by step i am begginer
![SharedScreenshot](https://user-images.githubusercontent.com/102432660/160253763-a5bdb2b2-eed8-41c3-be7d-690fffc5d194.jpg)

**Comment by TechSupportz** [comment]
Open `android > app > build.gradle` and then change both `compileSdkVersion` and `targetSdkVersion` to 31

Then open `android > app > src > main > AndroidManifest.xml `. Under the activity tag add `android:exported="true"` at the end. 

Re-run you app and it should work

**Comment by raghadromaneh** [comment]
thank you !
