### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by HTibs** [londonappbrewery/mi_card_flutter#8]
The following is the error:

 Android resource linking failed
  Output:  G:\FLUTTER_PROJECTS\downloaded\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  G:\FLUTTER_PROJECTS\downloaded\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\dell\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\569201ef15a0fc6c5b515a5d722c0da7\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\dell\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          G:\FLUTTER_PROJECTS\downloaded\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          G:\FLUTTER_PROJECTS\downloaded\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @G:\FLUTTER_PROJECTS\downloaded\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          G:\FLUTTER_PROJECTS\downloaded\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          G:\FLUTTER_PROJECTS\downloaded\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\dell\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\532176a0f783afb7cffda780024ab855\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

**Comment by hayyann** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/59503740/71767661-33aaf900-2f30-11ea-8c77-3b18b0978fa4.png)

I'm also getting the following error.

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\8795c7c7149d9230db0423e079c95a4d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\hayya\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\8785b1333ccfee40180d9ac1d1a63e1a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\8785b1333ccfee40180d9ac1d1a63e1a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\8795c7c7149d9230db0423e079c95a4d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\hayya\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by HTibs** [comment]
try these two changes it should work

**Comment by mcaubrey** [comment]
The project needs to be updated for [AndroidX](https://flutter.dev/docs/development/androidx-migration). In the meantime you can follow the instructions [here](https://flutter.dev/docs/development/androidx-migration).

It looks like this can be resolved by pull request #7

**Comment by TheMuellenator** [comment]
Just updated the stub. Bumped up the SDK and Gradle versions. 
Hope this fixes the issue. Let me know if the problems persist.
