### ISSUE TITLE
Getting error when running the mi_card_flutter code.

### ISSUE THREAD

**Issue by hayyann** [londonappbrewery/mi_card_flutter#9]
![Screenshot (1)](https://user-images.githubusercontent.com/59503740/71767685-7b318500-2f30-11ea-8397-6e1d6c370c5a.png)

I'm getting the following error.

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\8795c7c7149d9230db0423e079c95a4d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\hayya\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\8785b1333ccfee40180d9ac1d1a63e1a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\8785b1333ccfee40180d9ac1d1a63e1a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\8795c7c7149d9230db0423e079c95a4d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\hayya\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Lvka** [comment]
If you bump your compileSdkVersion from 27 to 28 in build.gradle you'll be able to build it successfully.

**Comment by TheMuellenator** [comment]
Just updated the stub. Bumped up the SDK and gradle versions. 
Hope this fixes the issue. Let me know if the problems persist.
